name: 'RouterTest'
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  angular2: '2.0.0-alpha.25'

transformers:
- angular2:
    entry_points:
        - web/main.dart
    reflection_entry_points:
        - web/main.dart
    mirror_mode: verbose
